version: '3'
services:
  pip-tools:
    build:
       context: .
       dockerfile: piptools.Dockerfile
    volumes:
      - .:/code
    command: pip-compile code/requirements.in
  db:
    image: postgres
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
